version: 1.0.1-alpha-{build}
os: Visual Studio 2015
init:
- git config --global core.autocrlf true
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
before_build:
- nuget restore

assembly_info:
  patch: true
  file: 'StyleCop.Analyzers\**\AssemblyInfo.*'
  assembly_version: 1.0.1.{build}
  assembly_file_version: 1.0.1.{build}
  assembly_informational_version: 1.0.1-alpha-{build}

configuration:
  - Release

build:
  project: StyleCopAnalyzers.sln
  verbosity: minimal

after_build:
- ps: >-
    cd build

    .\build.ps1

    cd..

test_script:
- .\packages\OpenCover.4.6.247-rc\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"C:\projects\stylecopanalyzers\StyleCop.Analyzers\StyleCop.Analyzers.Test\bin\%CONFIGURATION%\StyleCop.Analyzers.Test.dll -noshadow -appveyor" -returntargetcode -filter:"+[StyleCop*]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:.\StyleCopAnalyzers_coverage.xml
- "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- pip install codecov
- codecov -f "StyleCopAnalyzers_coverage.xml"
# preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
cache:
  - packages -> **\packages.config

artifacts:
  - path: build\nuget\*.nupkg

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/crumpstylecopanalyzers/api/v2/package
    symbol_server: https://nuget.symbolsource.org/MyGet/crumpstylecopanalyzers
    api_key:
      secure: SASQGWG/4zNns7bwSSsJ5RPvKcKfJsBeEPuw69wsVPA3PO739QmzVtc5VwQwgvbr
    artifact: /.*\.nupkg/
    on:
      branch: feature/MyGetCI